# LAW CONNECT V2 CONFIG   
# Eureka Service Registry Configuration 
eureka:
  instance:
    prefer-ip-address: true
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

# okta:
#   oauth2:
#     issuer: https://dev-90693819.okta.com/oauth2/default
#     audience: api://default

# Zipkin Config 
management:
  endpoints: 
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
